# Generated by Django 3.2.8 on 2021-11-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=30, verbose_name='项目code')),
                ('apiCode', models.CharField(max_length=30, verbose_name='apicode')),
                ('name', models.CharField(max_length=1024, verbose_name='标签')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内容')),
                ('isdefault', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=30, verbose_name='项目code')),
                ('apiCode', models.CharField(max_length=30, verbose_name='apicode')),
                ('apiname', models.CharField(max_length=50, verbose_name='接口名称')),
                ('httpType', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='HTTP', max_length=50, verbose_name='http/https')),
                ('requestType', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('apiAddress', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('requestParameterType', models.CharField(choices=[('form-data', '表单(form-data)'), ('raw', '源数据(raw)')], max_length=50, verbose_name='请求参数格式')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiRequestParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=30, verbose_name='项目code')),
                ('apiCode', models.CharField(max_length=30, verbose_name='apicode')),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='参数值')),
                ('isdefault', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=128)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP')),
                ('environmentName', models.CharField(max_length=100, verbose_name='环境名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('projectCode', models.CharField(max_length=30, verbose_name='项目code')),
                ('environmentDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcationName', models.CharField(max_length=30, unique=True, verbose_name='函数名称')),
                ('funcationCode', models.CharField(max_length=30, unique=True, verbose_name='函数code')),
                ('funcation', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30)),
                ('projectDescription', models.TextField()),
                ('projectCode', models.CharField(max_length=30, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqlName', models.CharField(max_length=200, unique=True, verbose_name='sql名称')),
                ('sqlCode', models.CharField(max_length=200, unique=True, verbose_name='sqlcode')),
                ('sql', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SqlConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=30, verbose_name='项目code')),
                ('environmentName', models.CharField(max_length=30, verbose_name='环境名称')),
                ('sqlconnectName', models.CharField(max_length=200, unique=True, verbose_name='sql连接名称')),
                ('sqlconnectCode', models.CharField(max_length=200, unique=True, verbose_name='sql连接code')),
                ('host', models.CharField(max_length=200, verbose_name='数据库连接地址 ')),
                ('port', models.IntegerField(verbose_name='数据库连接端口 ')),
                ('username', models.CharField(max_length=200, verbose_name='数据库连接用户名 ')),
                ('password', models.CharField(max_length=200, verbose_name='数据库连接地址 ')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=200, verbose_name='项目code')),
                ('testcaseName', models.CharField(max_length=200, verbose_name='用例名称')),
                ('testcaseCode', models.CharField(max_length=200, unique=True, verbose_name='用例code')),
                ('testcaseModel', models.CharField(max_length=200, verbose_name='用例所属模块')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcaseCode', models.CharField(max_length=200, verbose_name='用例code,对应用例表的testcaseCode')),
                ('testcaseDetailName', models.CharField(max_length=200, verbose_name='用例子元素的名称')),
                ('testcaseDetailCode', models.CharField(max_length=200, verbose_name='用例子元素的code')),
                ('testcaseDetailOrder', models.IntegerField(verbose_name='用例子元素的排序')),
                ('responsetransfer', models.CharField(max_length=500, verbose_name='response数据提取')),
                ('requesttransfer', models.CharField(max_length=500, verbose_name='request数据替换')),
                ('type', models.CharField(choices=[('API', 'API'), ('SQL', 'SQL'), ('TESTCASE', 'TESTCASE'), ('FUNCATION', 'FUNCATION'), ('ASSERT', 'ASSERT')], max_length=200, verbose_name='类型')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User2Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='用户电话')),
                ('projectCode', models.CharField(max_length=30, verbose_name='项目code')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=30, verbose_name='项目code')),
                ('environmentName', models.CharField(max_length=30, verbose_name='环境名称')),
                ('variableName', models.CharField(max_length=30, verbose_name='变量名称')),
                ('variable', models.CharField(max_length=30, verbose_name='变量值')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
