# Generated by Django 3.2.8 on 2021-11-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=200, verbose_name='项目code')),
                ('testcasesetName', models.CharField(max_length=200, verbose_name='用例集合名称')),
                ('testcasesetCode', models.CharField(max_length=200, unique=True, verbose_name='用例集合code')),
                ('testcaselist', models.CharField(max_length=500, verbose_name='包含的用例id')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
