# Generated by Django 3.2.8 on 2021-12-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_testcaseset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectCode', models.CharField(max_length=200, verbose_name='项目code')),
                ('testcasesetCode', models.CharField(blank=True, max_length=200, verbose_name='用例集合code')),
                ('testcaseCode', models.CharField(blank=True, max_length=200, verbose_name='用例code,对应用例表的testcaseCode')),
                ('result', models.CharField(default='PASS', max_length=200, verbose_name='用例或者用例集执行结果')),
                ('request', models.TextField(verbose_name='请求信息')),
                ('result_detail', models.TextField(verbose_name='用例执行的返回数据')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='httpType',
            field=models.CharField(choices=[('HTTPS', 'HTTPS'), ('HTTP', 'HTTP')], default='HTTP', max_length=50, verbose_name='http/https'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='requestParameterType',
            field=models.CharField(blank=True, choices=[('form-data', '表单(form-data)'), ('raw', '源数据(raw)'), ('no-params', '无参数')], max_length=50, verbose_name='请求参数格式'),
        ),
    ]
