# Generated by Django 3.2.10 on 2024-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20211220_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testcaseset',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
