# Generated by Django 3.2.10 on 2024-08-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_auto_20240819_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sql',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='sqlconnect',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
