# Generated by Django 3.2.10 on 2024-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_auto_20240825_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='variable',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
