# Generated by Django 3.2.10 on 2024-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_auto_20240825_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
